#
# <  MewX's Homepage - 11/23/2015 >
# This yml file refers serveral yml files, thanks to all open-source website projects.
#

# General setting
markdown: kramdown
encoding: utf-8

# Site info
#baseurl: http://www.mewx.org/
baseurl: ./
paginate: 10
permalink: blog/:year:month/:title
exclude: ["README.md", "changelog.md", "Gemfile.lock"]
gems: [jekyll-paginate]

# Blog info
title : MewX's Homepage
author: MewX
email : mewx(at)mewx(dot)org
#cdn   : http://7xn9yq.com1.z0.glb.clouddn.com/mewx/
cdn   : https://mewx.org/
#cdn   : http://127.0.0.1:4000/
